### PR TITLE
fixed infinite loop when jQuery is loaded

### LINKED ISSUE #154: Doesn't work with Angular 1.3
Testing the playground code and putting angular 1.3.0 there the lib goes in infinite loop and never render the chart

### PR DESCRIPTION
**Pull request by moumar**
this will fix #154

### CODE REVIEW

**Comment by stormboy** [comment]
This is an important fix.  I just spent a while narrowing down a JS lock-up and arrived at the exact same code change.  I am using bower to include this module.  Please merge.

**Comment by aclemmer** [comment]
Please merge. Also seeing the issue on angular 1.2.28; this fixes it.

**Comment by soyuka** [comment]
Merged but I can't publish to bower.

**Comment by moumar** [comment]
when using jQuery, additional props are added to arrays returned by .find() and are reached with "for(var i in ...)" syntax, causing an infinite loop. Proper "for" syntax fixes it.

**Comment by zzzaaa** [comment]
+1 for bower package

**Comment by philippecarle** [comment]
+1 for bower package………

**Comment by abhisharma2** [comment]
yes +1. updating bower would be great!

**Comment by PanfilovDenis** [comment]
+ 1 update bower package plz!

**Pull request merged**
